apiVersion: batch/v1
kind: Job
metadata:
  name: random-error
spec:
  completions: 3
  template:
    spec:
      containers:
        - name: random-error
          image: kodekloud/random-error
      restartPolicy: OnFailure

